// <auto-generated />
using System;
using Ecommerce.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Api.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    [Migration("20250821222829_AddIsDeletedToSaleModel")]
    partial class AddIsDeletedToSaleModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Api.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Shoes",
                            IsDeleted = false
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Socks",
                            IsDeleted = false
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Pants",
                            IsDeleted = false
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Shirts",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Ecommerce.Api.Models.LineItem", b =>
                {
                    b.Property<int>("LineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineItemId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LineItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("LineItems", (string)null);

                    b.HasData(
                        new
                        {
                            LineItemId = 1,
                            ProductId = 8,
                            Quantity = 1,
                            SaleId = 1,
                            UnitPrice = 22.99m
                        },
                        new
                        {
                            LineItemId = 2,
                            ProductId = 6,
                            Quantity = 1,
                            SaleId = 2,
                            UnitPrice = 45.95m
                        },
                        new
                        {
                            LineItemId = 3,
                            ProductId = 3,
                            Quantity = 1,
                            SaleId = 2,
                            UnitPrice = 15.25m
                        },
                        new
                        {
                            LineItemId = 4,
                            ProductId = 7,
                            Quantity = 1,
                            SaleId = 3,
                            UnitPrice = 34.75m
                        },
                        new
                        {
                            LineItemId = 5,
                            ProductId = 6,
                            Quantity = 1,
                            SaleId = 3,
                            UnitPrice = 45.95m
                        },
                        new
                        {
                            LineItemId = 6,
                            ProductId = 1,
                            Quantity = 1,
                            SaleId = 3,
                            UnitPrice = 75.50m
                        },
                        new
                        {
                            LineItemId = 7,
                            ProductId = 2,
                            Quantity = 2,
                            SaleId = 4,
                            UnitPrice = 53.75m
                        },
                        new
                        {
                            LineItemId = 8,
                            ProductId = 4,
                            Quantity = 2,
                            SaleId = 5,
                            UnitPrice = 10.15m
                        },
                        new
                        {
                            LineItemId = 9,
                            ProductId = 1,
                            Quantity = 1,
                            SaleId = 5,
                            UnitPrice = 75.50m
                        });
                });

            modelBuilder.Entity("Ecommerce.Api.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            IsDeleted = false,
                            Price = 75.50m,
                            ProductName = "Hightop Sneakers"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            IsDeleted = false,
                            Price = 53.75m,
                            ProductName = "Boat Loafers"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            IsDeleted = false,
                            Price = 15.25m,
                            ProductName = "Dress Socks"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            IsDeleted = false,
                            Price = 10.15m,
                            ProductName = "Ankle Socks"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 3,
                            IsDeleted = false,
                            Price = 35.99m,
                            ProductName = "Dress Slacks"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 3,
                            IsDeleted = false,
                            Price = 45.95m,
                            ProductName = "Stonewash Jeans"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 4,
                            IsDeleted = false,
                            Price = 34.75m,
                            ProductName = "Flannel Shirt"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 4,
                            IsDeleted = false,
                            Price = 22.99m,
                            ProductName = "Shortsleeve Polo"
                        });
                });

            modelBuilder.Entity("Ecommerce.Api.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("DateAndTimeOfSale")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sales", (string)null);

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            DateAndTimeOfSale = new DateTime(2025, 8, 1, 12, 37, 22, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TotalPrice = 22.99m
                        },
                        new
                        {
                            SaleId = 2,
                            DateAndTimeOfSale = new DateTime(2025, 8, 3, 14, 30, 48, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TotalPrice = 61.20m
                        },
                        new
                        {
                            SaleId = 3,
                            DateAndTimeOfSale = new DateTime(2025, 8, 7, 11, 39, 10, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TotalPrice = 156.20m
                        },
                        new
                        {
                            SaleId = 4,
                            DateAndTimeOfSale = new DateTime(2025, 8, 7, 19, 13, 55, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TotalPrice = 107.50m
                        },
                        new
                        {
                            SaleId = 5,
                            DateAndTimeOfSale = new DateTime(2025, 8, 8, 9, 4, 17, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            TotalPrice = 95.80m
                        });
                });

            modelBuilder.Entity("Ecommerce.Api.Models.LineItem", b =>
                {
                    b.HasOne("Ecommerce.Api.Models.Product", "Product")
                        .WithMany("LineItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Api.Models.Sale", "Sale")
                        .WithMany("LineItems")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Ecommerce.Api.Models.Product", b =>
                {
                    b.HasOne("Ecommerce.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ecommerce.Api.Models.Product", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("Ecommerce.Api.Models.Sale", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
