// <auto-generated />
using System;
using JafnaEcommerceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JafnaEcommerceApi.Migrations
{
    [DbContext(typeof(JafnaDbContext))]
    [Migration("20251128104627_adddata")]
    partial class adddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JafnaEcommerceApi.Models.Entities.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("deleted_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("category");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2025, 11, 28, 10, 46, 27, 110, DateTimeKind.Utc).AddTicks(2478),
                            is_deleted = false,
                            name = "Fish"
                        },
                        new
                        {
                            id = 2,
                            created_date = new DateTime(2025, 11, 28, 10, 46, 27, 110, DateTimeKind.Utc).AddTicks(2482),
                            is_deleted = false,
                            name = "Plants"
                        },
                        new
                        {
                            id = 3,
                            created_date = new DateTime(2025, 11, 28, 10, 46, 27, 110, DateTimeKind.Utc).AddTicks(2484),
                            is_deleted = false,
                            name = "Aquarium Supplies"
                        });
                });

            modelBuilder.Entity("JafnaEcommerceApi.Models.Entities.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("deleted_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            category_id = 1,
                            created_date = new DateTime(2025, 11, 28, 10, 46, 27, 110, DateTimeKind.Utc).AddTicks(2764),
                            description = "Beautiful hardy goldfish",
                            image = "goldfish.jpg",
                            is_deleted = false,
                            name = "Goldfish",
                            price = 100m
                        },
                        new
                        {
                            id = 2,
                            category_id = 2,
                            created_date = new DateTime(2025, 11, 28, 10, 46, 27, 110, DateTimeKind.Utc).AddTicks(2768),
                            description = "Popular aquarium plant",
                            image = "amazonsword.jpg",
                            is_deleted = false,
                            name = "Amazon Sword",
                            price = 150m
                        },
                        new
                        {
                            id = 3,
                            category_id = 3,
                            created_date = new DateTime(2025, 11, 28, 10, 46, 27, 110, DateTimeKind.Utc).AddTicks(2770),
                            description = "Small internal filter",
                            image = "filter.jpg",
                            is_deleted = false,
                            name = "Internal Filter",
                            price = 500m
                        });
                });

            modelBuilder.Entity("JafnaEcommerceApi.Models.Entities.Sale", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("total_price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id");

                    b.ToTable("sale");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2025, 11, 28, 10, 46, 27, 110, DateTimeKind.Utc).AddTicks(2799),
                            total_price = 200m
                        });
                });

            modelBuilder.Entity("JafnaEcommerceApi.Models.Entities.SaleDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("product_price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("product_quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("product_total_price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("sale_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.HasIndex("sale_id");

                    b.ToTable("sale_details");

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_date = new DateTime(2025, 11, 28, 10, 46, 27, 110, DateTimeKind.Utc).AddTicks(2831),
                            product_id = 1,
                            product_name = "Goldfish",
                            product_price = 100m,
                            product_quantity = 2,
                            product_total_price = 200m,
                            sale_id = 1
                        });
                });

            modelBuilder.Entity("JafnaEcommerceApi.Models.Entities.Product", b =>
                {
                    b.HasOne("JafnaEcommerceApi.Models.Entities.Category", "category")
                        .WithMany("Products")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("JafnaEcommerceApi.Models.Entities.SaleDetail", b =>
                {
                    b.HasOne("JafnaEcommerceApi.Models.Entities.Product", "Product")
                        .WithMany("SaleDetails")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JafnaEcommerceApi.Models.Entities.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("sale_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("JafnaEcommerceApi.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("JafnaEcommerceApi.Models.Entities.Product", b =>
                {
                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("JafnaEcommerceApi.Models.Entities.Sale", b =>
                {
                    b.Navigation("SaleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
