// <auto-generated />
using System;
using ExerciseTracker.SpyrosZoupas.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExerciseTracker.SpyrosZoupas.Migrations
{
    [DbContext(typeof(ExerciseTrackerDbContext))]
    [Migration("20250516224609_rename-and-add-mass")]
    partial class renameandaddmass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExerciseTracker.SpyrosZoupas.DAL.Model.WeightExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<double>("Mass")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("WeightExercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "My first exercise!",
                            DateEnd = new DateTime(2025, 2, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Mass = 5.0
                        },
                        new
                        {
                            Id = 2,
                            Comments = "My second exercise 8)",
                            DateEnd = new DateTime(2025, 1, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Mass = 10.0
                        },
                        new
                        {
                            Id = 3,
                            Comments = "",
                            DateEnd = new DateTime(2026, 1, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2026, 1, 1, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Mass = 11.0
                        },
                        new
                        {
                            Id = 4,
                            Comments = "",
                            DateEnd = new DateTime(2025, 11, 10, 0, 0, 50, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mass = 15.0
                        },
                        new
                        {
                            Id = 5,
                            Comments = "My final exercise!",
                            DateEnd = new DateTime(2026, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Mass = 20.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
