// <auto-generated />
using System;
using EcommerceAPI.Ledana.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceAPI.Ledana.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20260515121617_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcommerceAPI.Ledana.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Peripherals"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monitors and Displays"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Computers and Laptops"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Components"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Audio and Headsets"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Video and Cameras"
                        });
                });

            modelBuilder.Entity("EcommerceAPI.Ledana.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Wireless Mouse",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Nose Cancelling HeadPhones",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Silent Keyboard",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Curved Monitor",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "All Surface Projector",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Wide 4K Monitor",
                            Price = 219.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Gaming Laptop",
                            Price = 899.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Workstation PC",
                            Price = 1029.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Name = "CPU",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Name = "GPU",
                            Price = 109.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Name = "RAM",
                            Price = 489.99m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "SSD",
                            Price = 119.99m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Name = "Gaming Headset",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Name = "Studio Mic",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            Name = "Webcam",
                            Price = 215.99m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Name = "Capture Card",
                            Price = 708.99m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Name = "360 Camera",
                            Price = 4009.99m
                        });
                });

            modelBuilder.Entity("EcommerceAPI.Ledana.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 4, 30, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 5, 2, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 5, 3, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2026, 5, 4, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EcommerceAPI.Ledana.Models.SaleProduct", b =>
                {
                    b.Property<int>("SalesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("([Quantity] * [UnitPriceAtSale]) * (1 - [Discount])", true);

                    b.Property<decimal>("UnitPriceAtSale")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SalesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("SaleProduct");

                    b.HasData(
                        new
                        {
                            SalesId = 1,
                            ProductsId = 1,
                            Discount = 0.10m,
                            Quantity = 2,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 9.99m
                        },
                        new
                        {
                            SalesId = 2,
                            ProductsId = 1,
                            Discount = 0m,
                            Quantity = 1,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 9.99m
                        },
                        new
                        {
                            SalesId = 1,
                            ProductsId = 3,
                            Discount = 0.05m,
                            Quantity = 2,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 19.99m
                        },
                        new
                        {
                            SalesId = 2,
                            ProductsId = 4,
                            Discount = 0.20m,
                            Quantity = 2,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 599.99m
                        },
                        new
                        {
                            SalesId = 3,
                            ProductsId = 5,
                            Discount = 0.10m,
                            Quantity = 1,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 129.99m
                        },
                        new
                        {
                            SalesId = 3,
                            ProductsId = 7,
                            Discount = 0m,
                            Quantity = 1,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 899.99m
                        },
                        new
                        {
                            SalesId = 3,
                            ProductsId = 8,
                            Discount = 0.05m,
                            Quantity = 1,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 1029.99m
                        },
                        new
                        {
                            SalesId = 2,
                            ProductsId = 5,
                            Discount = 0.20m,
                            Quantity = 2,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 129.99m
                        },
                        new
                        {
                            SalesId = 4,
                            ProductsId = 15,
                            Discount = 0.10m,
                            Quantity = 1,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 215.99m
                        },
                        new
                        {
                            SalesId = 4,
                            ProductsId = 9,
                            Discount = 0m,
                            Quantity = 1,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 299.99m
                        },
                        new
                        {
                            SalesId = 4,
                            ProductsId = 8,
                            Discount = 0.05m,
                            Quantity = 1,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 1029.99m
                        },
                        new
                        {
                            SalesId = 4,
                            ProductsId = 5,
                            Discount = 0.20m,
                            Quantity = 2,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 129.99m
                        },
                        new
                        {
                            SalesId = 5,
                            ProductsId = 11,
                            Discount = 0.10m,
                            Quantity = 1,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 489.99m
                        },
                        new
                        {
                            SalesId = 5,
                            ProductsId = 12,
                            Discount = 0m,
                            Quantity = 1,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 119.99m
                        },
                        new
                        {
                            SalesId = 4,
                            ProductsId = 17,
                            Discount = 0.05m,
                            Quantity = 1,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 4009.99m
                        },
                        new
                        {
                            SalesId = 5,
                            ProductsId = 1,
                            Discount = 0.20m,
                            Quantity = 2,
                            TotalPrice = 0m,
                            UnitPriceAtSale = 9.99m
                        });
                });

            modelBuilder.Entity("EcommerceAPI.Ledana.Models.Product", b =>
                {
                    b.HasOne("EcommerceAPI.Ledana.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EcommerceAPI.Ledana.Models.SaleProduct", b =>
                {
                    b.HasOne("EcommerceAPI.Ledana.Models.Product", "Product")
                        .WithMany("SaleProducts")
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceAPI.Ledana.Models.Sale", "Sale")
                        .WithMany("SaleProducts")
                        .HasForeignKey("SalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("EcommerceAPI.Ledana.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EcommerceAPI.Ledana.Models.Product", b =>
                {
                    b.Navigation("SaleProducts");
                });

            modelBuilder.Entity("EcommerceAPI.Ledana.Models.Sale", b =>
                {
                    b.Navigation("SaleProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
